#!/bin/sh
# This script is executed at boot time before VyOS configuration is applied.
# Any modifications required to work around unfixed bugs or use
# services not available through the VyOS CLI system can be placed here.

# BBR for congestion protocol
# https://forum.vyos.io/t/recommended-network-configuration/12037/2
/sbin/modprobe tcp_bbr

# Fix for containers requiring a custom user/group id
# and Vyos not preserving file perms on upgrade
